server:
  port: 8086

spring:
  application:
    name: ms-laboratorio
  
  datasource:
    url: jdbc:mysql://localhost:3306/db_laboratorio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root  # <-- Tu clave de MySQL local
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop # Limpia las tablas al arrancar para poblar con DataFaker desde cero
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    status-page-url-path: /