server:
  port: 8081

spring:
  application:
    name: ms-paciente
  datasource:
    # Conexión directa a Aiven con SSL habilitado si no existen variables de entorno
    url: jdbc:mysql://${DB_HOST:mysql-26a1585c-centro-medico.g.aivencloud.com:12885}/${DB_NAME:defaultdb}?useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:avnadmin}
    password: ${DB_PASSWORD:AVNS_FOJHhGkvfWqMm2wauK8}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # 👈 Dejado tal cual para que el DataFaker cargue los datos falsos en cada inicio
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 👇 SECCIÓN EUREKA 👇
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    status-page-url-path: /