server:
  port: 8087

spring:
  application:
    name: ms-factura
  
  datasource:
    url: jdbc:mysql://localhost:3306/db_factura?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root  # 👈 Pon aquí tu contraseña local de MySQL si es distinta
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop # Borra y crea las tablas limpias al arrancar para meter el DataFaker
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    status-page-url-path: /  # Esto hace que el link de Eureka apunte directo a tu RaizController (el JSON)
    instance-id: ${spring.application.name}:${server.port}