server:
  port: 8083

spring:
  application:
    name: ms-cita
  
  datasource:
    # Híbrido: Si detecta AWS usa DB_HOST, si no, vuelve a tu localhost:3306/db_citas local
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:db_citas}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}  # <-- Tu clave de MySQL aquí
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    status-page-url-path: /